[package]
name = "scan_world"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] } #, "tracing"
sysinfo = "0.30.12"

[profile.release]
lto = true
codegen-units = 1
strip=true
panic = 'abort'